import type { Metadata } from "next";
import "./globals.css";
import ScrollToTop from "@/components/common/ScrollToTop";

export const metadata: Metadata = {
  title: "prepco",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <ScrollToTop /> 
      </body>
    </html>
  );
}
